# Q1)You have to create an in Numpy and perform basic operations on the array using Numpy. such as reshaping, indexing, slicing, and iterating.

In [18]:
import numpy as np #Aliasing - faster than having to type 'numpy' everytime

## Creating an Array

In [19]:
a = np.array([1,2,3])
b = np.array([ [1,2,3], [4,5,6] ])
c = np.array([ [1,3,5,7], [2,4,6,8] ])
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 3 5 7]
 [2 4 6 8]]


## Creating an Array with a specified DataType

In [20]:
d = np.array([2,3,5,7,9])
print(d.dtype)

#int32 => 32 bits is the size of each element i.e. 4 bytes.

f_array = np.array([2,4,6,7,8], dtype = 'float16') 
print(f_array.dtype)

##to change  datatype, use: f_array.astype(np.int32)

int32
float16


##  (I) Basics

In [21]:
dim_a = a.ndim
dim_b = b.ndim
print(dim_a)
print(dim_b)

1
2


In [22]:
#Get the dimensions of c:
dim_c = c.ndim
print(dim_c)

2


In [23]:
shape_a = a.shape
shape_b = b.shape
print(shape_a)
print(shape_b)

(3,)
(2, 3)


In [24]:
size_a = a.itemsize
print(size_a)

print(b.itemsize)

4
4


In [25]:
print(a.size)
size_b = b.size
print(size_b)
#print(c.size)

3
6


In [26]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
#Access 8 in a:
print(a[1,2])
#Access 11 
print(a[2,0])
#Access 19
print(a[-2,-2])

8
11
19


In [28]:
#To access the second row of a, do:
second_row = a[1,:]
print(second_row)

[ 6  7  8  9 10]


In [29]:
#access last row:
print(a[-1,:])

[21 22 23 24 25]


In [31]:
#To access the first column:
first_column = a[:,0]
print(first_column)

last_column = a[:,-1]
print(last_column)

[ 1  6 11 16 21]
[ 5 10 15 20 25]


In [32]:
#access 4th column:
print(a[:,-2])
#access 2nd column:
print(a[:,1])

[ 4  9 14 19 24]
[ 2  7 12 17 22]


In [33]:
#syntax: a[start index : end index : step]
#For example, suppose we have to access elements from 10 to 12. Then do:
array1 = a[2,1:4:1]
print(array1)

#Second example: access elements 13 and 15

[12 13 14]


In [34]:
#Block accessing 1 - step = 1
#Access 11,12,16,17
print(a[2:4:1,0:2:1])

#Block accessing 2 - step = 1
#Access 8,9,10,13,14,15,18,19,20
print(a[1:4:1,2:5:1])

#Block accessing 3 - step = 2
#Access 1,3,5,11,13,15,21,23,25
print(a[0:5:2,0:5:2])

#Diagonal accessing
#Access 2,8,14,20
print(a[[0,1,2,3],[1,2,3,4]])

#Random Accessing
#Access 4,5,14,15,19,20
print(a[[0,2,3],3:5:1])

[[11 12]
 [16 17]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[ 2  8 14 20]
[[ 4  5]
 [14 15]
 [19 20]]


In [35]:
x = a[[4,3,2,1,0],[0,1,2,3,4]]
y = a[0:5:1,0:3:1]
z = a[[0,1,3,4],0:2:1]
w = a[0:4:1,0:2:1]
print(a[[0,1,3,4],0:3:1])

[[ 1  2  3]
 [ 6  7  8]
 [16 17 18]
 [21 22 23]]


In [36]:
#Now that we've learnt how to access a particular element, it's quite simple to change 
#that accessed element(s).
#For example, if we want to change 10 to 100, we access 10 and change it to 100 by :
a[1,4] = 100
print(a)


[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


In [37]:
#Change 20 to 200
a[3,4]=200
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 11  12  13  14  15]
 [ 16  17  18  19 200]
 [ 21  22  23  24  25]]


In [38]:
#make it so that all the elements in the last row are 50
a[4,:]=50
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 11  12  13  14  15]
 [ 16  17  18  19 200]
 [ 50  50  50  50  50]]


In [40]:
#Change all the elements of the third row to 72
a[2,:]=72
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 72  72  72  72  72]
 [ 16  17  18  19 200]
 [ 50  50  50  50  50]]


In [41]:
#make it so that all the elements of the last column are 80 
a[:,4]=80
print(a)

[[ 1  2  3  4 80]
 [ 6  7  8  9 80]
 [72 72 72 72 80]
 [16 17 18 19 80]
 [50 50 50 50 80]]


In [42]:
#Make it so that all the elements in the second column are 77
a[:,1]=77
print(a)

[[ 1 77  3  4 80]
 [ 6 77  8  9 80]
 [72 77 72 72 80]
 [16 77 18 19 80]
 [50 77 50 50 80]]


In [43]:
a= np.array([[1,2,3,4],[5,6,7,8]])
b= a.reshape((8,1)) #8rows and 1 column
print(b)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [44]:
#Modify array a such that it becomes a 4x2, 2x2x2 array
c = a.reshape((4,2))
d = a.reshape((2,2,2))
print(c)
print("--------")
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Q2)In pandas You have to download any dataset from Kaggle. and import the dataset and perform cleaning functions on the dataset.

# Importing Essential Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Loading the dataset

In [4]:
df=pd.read_csv("IPL Data Set.csv")

# Exploring the dataset



In [5]:
df

mid        date                                      venue  \
0        1  18-04-2008                      M Chinnaswamy Stadium   
1        1  18-04-2008                      M Chinnaswamy Stadium   
2        1  18-04-2008                      M Chinnaswamy Stadium   
3        1  18-04-2008                      M Chinnaswamy Stadium   
4        1  18-04-2008                      M Chinnaswamy Stadium   
...    ...         ...                                        ...   
76009  617  21-05-2017  Rajiv Gandhi International Stadium, Uppal   
76010  617  21-05-2017  Rajiv Gandhi International Stadium, Uppal   
76011  617  21-05-2017  Rajiv Gandhi International Stadium, Uppal   
76012  617  21-05-2017  Rajiv Gandhi International Stadium, Uppal   
76013  617  21-05-2017  Rajiv Gandhi International Stadium, Uppal   

                batting_team                 bowling_team      batsman  \
0      Kolkata Knight Riders  Royal Challengers Bangalore   SC Ganguly   
1      Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum   
2      Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum   
3      Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum   
4      Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum   
...                      ...                          ...          ...   
76009         Mumbai Indians       Rising Pune Supergiant    KH Pandya   
76010         Mumbai Indians       Rising Pune Supergiant    KH Pandya   
76011         Mumbai Indians       Rising Pune Supergiant    KH Pandya   
76012         Mumbai Indians       Rising Pune Supergiant   MG Johnson   
76013         Mumbai Indians       Rising Pune Supergiant    KH Pandya   

             bowler  runs  wickets  overs  runs_last_5  wickets_last_5  \
0           P Kumar     1        0    0.1            1               0   
1           P Kumar     1        0    0.2            1               0   
2           P Kumar     2        0    0.2            2               0   
3           P Kumar     2        0    0.3            2               0   
4           P Kumar     2        0    0.4            2               0   
...             ...   ...      ...    ...          ...             ...   
76009  DT Christian   121        7   19.2           40               0   
76010  DT Christian   127        7   19.3           46               0   
76011  DT Christian   128        7   19.4           47               0   
76012  DT Christian   129        7   19.5           48               0   
76013  DT Christian   129        8   19.6           47               1   

       striker  non-striker  total  
0            0            0    222  
1            0            0    222  
2            0            0    222  
3            0            0    222  
4            0            0    222  
...        ...          ...    ...  
76009       40           12    129  
76010       46           12    129  
76011       47           12    129  
76012       47           13    129  
76013       47           13    129  

[76014 rows x 15 columns]

In [6]:
df.dtypes

mid                 int64
date               object
venue              object
batting_team       object
bowling_team       object
batsman            object
bowler             object
runs                int64
wickets             int64
overs             float64
runs_last_5         int64
wickets_last_5      int64
striker             int64
non-striker         int64
total               int64
dtype: object

# Data Cleaning

### Removing unwanted columns • Keeping only consistent teams • Removing the first 5 overs data set in every match • Converting the column 'date' from string into datetime object

In [7]:
df.columns

Index(['mid', 'date', 'venue', 'batting_team', 'bowling_team', 'batsman',
       'bowler', 'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5',
       'striker', 'non-striker', 'total'],
      dtype='object')

In [8]:
# Removing unwanted columns and keeping the rows as it is 
columns_to_remove = ['mid', 'venue', 'batsman', 'bowler', 'striker', 'non-striker']

print('Before removing unwanted columns: {}'.format(df.shape))
df.drop(labels=columns_to_remove, axis=1, inplace=True)
print('After removing unwanted columns: {}'.format(df.shape))

Before removing unwanted columns: (76014, 15)
After removing unwanted columns: (76014, 9)


In [9]:
df.columns

Index(['date', 'batting_team', 'bowling_team', 'runs', 'wickets', 'overs',
       'runs_last_5', 'wickets_last_5', 'total'],
      dtype='object')

In [10]:
df

date           batting_team                 bowling_team  runs  \
0      18-04-2008  Kolkata Knight Riders  Royal Challengers Bangalore     1   
1      18-04-2008  Kolkata Knight Riders  Royal Challengers Bangalore     1   
2      18-04-2008  Kolkata Knight Riders  Royal Challengers Bangalore     2   
3      18-04-2008  Kolkata Knight Riders  Royal Challengers Bangalore     2   
4      18-04-2008  Kolkata Knight Riders  Royal Challengers Bangalore     2   
...           ...                    ...                          ...   ...   
76009  21-05-2017         Mumbai Indians       Rising Pune Supergiant   121   
76010  21-05-2017         Mumbai Indians       Rising Pune Supergiant   127   
76011  21-05-2017         Mumbai Indians       Rising Pune Supergiant   128   
76012  21-05-2017         Mumbai Indians       Rising Pune Supergiant   129   
76013  21-05-2017         Mumbai Indians       Rising Pune Supergiant   129   

       wickets  overs  runs_last_5  wickets_last_5  total  
0            0    0.1            1               0    222  
1            0    0.2            1               0    222  
2            0    0.2            2               0    222  
3            0    0.3            2               0    222  
4            0    0.4            2               0    222  
...        ...    ...          ...             ...    ...  
76009        7   19.2           40               0    129  
76010        7   19.3           46               0    129  
76011        7   19.4           47               0    129  
76012        7   19.5           48               0    129  
76013        8   19.6           47               1    129  

[76014 rows x 9 columns]

In [11]:
df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [12]:
consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
                    'Mumbai Indians', 'Kings XI Punjab', 'Royal Challengers Bangalore',
                    'Delhi Daredevils', 'Sunrisers Hyderabad']

In [13]:
# Keeping only consistent teams
print('Before removing inconsistent teams: {}'.format(df.shape))
df = df[(df['batting_team'].isin(consistent_teams)) & (df['bowling_team'].isin(consistent_teams))]
print('After removing inconsistent teams: {}'.format(df.shape))

Before removing inconsistent teams: (76014, 9)
After removing inconsistent teams: (53811, 9)


In [14]:
df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Kings XI Punjab', 'Royal Challengers Bangalore',
       'Delhi Daredevils', 'Sunrisers Hyderabad'], dtype=object)

In [15]:
# Removing the first 5 overs data in every match
print('Before removing first 5 overs data: {}'.format(df.shape))
df = df[df['overs']>=5.0]
print('After removing first 5 overs data: {}'.format(df.shape))

Before removing first 5 overs data: (53811, 9)
After removing first 5 overs data: (40108, 9)


In [16]:
# Converting the column 'date' from string into datetime object
from datetime import datetime
print("Before converting 'date' column from string to datetime object: {}".format(type(df.iloc[0,0])))
df['date'] = df['date'].apply(lambda x: datetime.strptime(x, '%d-%m-%Y'))
print("After converting 'date' column from string to datetime object: {}".format(type(df.iloc[0,0])))


Before converting 'date' column from string to datetime object: <class 'str'>
After converting 'date' column from string to datetime object: <class 'pandas._libs.tslibs.timestamps.Timestamp'>


In [17]:
df

date           batting_team                 bowling_team  runs  \
32    2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
33    2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
34    2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
35    2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
36    2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
...          ...                    ...                          ...   ...   
75884 2017-05-19  Kolkata Knight Riders               Mumbai Indians   106   
75885 2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75886 2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75887 2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75888 2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   

       wickets  overs  runs_last_5  wickets_last_5  total  
32           0    5.1           59               0    222  
33           1    5.2           59               1    222  
34           1    5.3           59               1    222  
35           1    5.4           59               1    222  
36           1    5.5           58               1    222  
...        ...    ...          ...             ...    ...  
75884        9   18.1           29               4    107  
75885        9   18.2           29               4    107  
75886        9   18.3           28               4    107  
75887        9   18.4           24               4    107  
75888       10   18.5           23               5    107  

[40108 rows x 9 columns]